### ISSUE TITLE
Use variables for api key

### ISSUE THREAD

**Issue by keyurshah** [lojabasico/shopify-postman#1]
love this collection! thanks so much.

wondering if there was a reason you didn't use the built in variables feature?

https://www.getpostman.com/docs/environments

this way you wouldn't need to do a search/replace and can maintain the api keys in one spot and for multiple stores.

**Comment by keyurshah** [comment]
I created a version with the hardcoded keys switched to variables. you don't have to pull it, I just wanted to make it available in case anyone needed it.

Thanks! 

#2

**Comment by renatodex** [comment]
Amazing!
Didn't knew about Postman variables, its really great!
I will merge your commit and change the Readme instructions!

**Comment by keyurshah** [comment]
Thanks so much!
